const Storage = require('../models/storageModel');
const AppError = require('../utils/appError');
const handlerFactory = require('../utils/handlerFactory');
const catchAsync = require('../utils/catchAsync');
exports.getstorage = handlerFactory.getOne(Storage);
exports.createstorage = handlerFactory.createOne(Storage);
exports.updatestorage = handlerFactory.updateOne(Storage);
exports.deletestorage = handlerFactory.deleteOne(Storage);
exports.getAllstorage = handlerFactory.getAll(Storage);
